name = "GenieBDD"
uuid = "38eb4f01-f086-4b2c-bbea-8af5d8f865c6"
authors = ["<>"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
